apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecow-deployment
  labels:
    app: wisecow
spec:
  replicas: 1   # number of pods
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecow
        image: harsh042/wisecow:latest   # <-- your Docker Hub image
        imagePullPolicy: Always
        ports:
        - containerPort: 4499
