name: CI/CD for Wisecow

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=harsh042/wisecow
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      # Setup kubectl
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.30.0   # Adjust to your cluster version

      # Configure K8s (using kubeconfig secret)
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_CONTENT }}" > $HOME/.kube/config

      # Deploy to Kubernetes
      - name: Deploy to Minikube / Cluster
        run: |
          kubectl apply -f k8s/

      # Verify rollout
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/wisecow-deployment
          kubectl get svc wisecow-service -o wide
