name: CI/CD for Wisecow

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: Ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=harsh042/wisecow
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

      # Deploy to Kubernetes
      - name: Deploy to Minikube / Cluster
        run: |
          kubectl apply -f k8s/

      # Verify rollout
      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/wisecow-deployment
          kubectl get svc wisecow-service -o wide
